/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_aion_crypto_hash_Blake2bNative */

#ifndef _Included_org_aion_crypto_hash_Blake2bNative
#define _Included_org_aion_crypto_hash_Blake2bNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_aion_crypto_hash_Blake2bNative
 * Method:    blake256
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_aion_crypto_hash_Blake2bNative_blake256
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
